INSERT INTO `ftsy_scoring_hist`(
	`season_id`
	, `season_name`
	, `round_name`
	, `fixture_id`
	, `player_id`
	, `display_name`
	, `common_name`
	, `number`
	, `position_short`
	, `injured`
	, `injury_reason`
	, `is_suspended`
	, `is_sidelined`
	, `image_path`
	, `current_team_id`
	, `team_name`
	, `team_code`
	, `logo_path`
	, `1_ftsy_owner_type`
	, `1_ftsy_owner_id`
	, `1_ftsy_match_status`
	, `2_ftsy_owner_type`
	, `2_ftsy_owner_id`
	, `2_ftsy_match_status`
	, `kickoff_dt`
	, `kickoff_ts`
	, `kickoff_time`
	, `homeaway`
	, `opp_team_name`
	, `opp_team_code`
	, `opp_team_id`
	, `score_for`
	, `score_against`
	, `ftsy_score`
	, `appearance_ftsy`
	, `appearance_stat`
	, `captain_ftsy`
	, `captain_stats`
	, `minutes_played_ftsy`
	, `minutes_played_stat`
	, `clean_sheet_ftsy`
	, `clean_sheet_stat`
	, `goals_made_ftsy`
	, `goals_made_stat`
	, `penalties_made_ftsy`
	, `penalties_made_stat`
	, `assists_made_ftsy`
	, `assists_made_stat`
	, `owngoals_ftsy`
	, `owngoals_stat`
	, `redcards_ftsy`
	, `redcards_stat`
	, `yellowredcards_ftsy`
	, `yellowredcards_stat`
	, `dribble_attempts_ftsy`
	, `dribble_attempts_stat`
	, `dribble_success_ftsy`
	, `dribble_success_stat`
	, `dribble_fail_ftsy`
	, `dribble_fail_stat`
	, `dribbled_past_ftsy`
	, `dribbled_past_stat`
	, `duels_total_ftsy`
	, `duels_total_stat`
	, `duels_won_ftsy`
	, `duels_won_stat`
	, `duels_lost_ftsy`
	, `duels_lost_stat`
	, `fouls_drawn_ftsy`
	, `fouls_drawn_stat`
	, `fouls_committed_ftsy`
	, `fouls_committed_stat`
	, `shots_total_ftsy`
	, `shots_total_stat`
	, `shots_on_goal_ftsy`
	, `shots_on_goal_stat`
	, `shots_missed_ftsy`
	, `shots_missed_stat`
	, `shots_on_goal_saved_ftsy`
	, `shots_on_goal_saved_stat`
	, `crosses_total_ftsy`
	, `crosses_total_stat`
	, `crosses_complete_ftsy`
	, `crosses_complete_stat`
	, `crosses_incomplete_ftsy`
	, `crosses_incomplete_stat`
	, `passes_total_ftsy`
	, `passes_total_stat`
	, `passes_complete_ftsy`
	, `passes_complete_stat`
	, `passes_incomplete_ftsy`
	, `passes_incomplete_stat`
	, `passes_key_ftsy`
	, `passes_key_stat`
	, `blocks_ftsy`
	, `blocks_stat`
	, `clearances_ftsy`
	, `clearances_stat`
	, `dispossessed_ftsy`
	, `dispossessed_stat`
	, `hit_woodwork_ftsy`
	, `hit_woodwork_stat`
	, `interceptions_ftsy`
	, `interceptions_stat`
	, `offsides_ftsy`
	, `offsides_stat`
	, `tackles_ftsy`
	, `tackles_stat`
	, `inside_box_saves_ftsy`
	, `inside_box_saves_stat`
	, `outside_box_saves_ftsy`
	, `outside_box_saves_stat`
	, `saves_ftsy`
	, `saves_stat`
	, `pen_committed_ftsy`
	, `pen_committed_stat`
	, `pen_missed_ftsy`
	, `pen_missed_stat`
	, `pen_saved_ftsy`
	, `pen_saved_stat`
	, `pen_won_ftsy`
	, `pen_won_stat`
	) 

SELECT 	fix.season_id
				, fix.season_name
				, fix.round_name
				, fix.fixture_id
				, base.id
				, base.display_name
				, base.common_name
        , base.number
        , base.position_short
        , base.injured
        , base.injury_reason
        , base.is_suspended
        , base.is_sidelined
        , base.image_path
        , base.current_team_id
        , base.name 
        , base.short_code 
        , base.logo_path 
        , base.1_ftsy_owner_type
        , base.1_ftsy_owner_id
        , base.1_ftsy_match_status
        , base.2_ftsy_owner_type
        , base.2_ftsy_owner_id
        , base.2_ftsy_match_status
        , fix.kickoff_dt
        , fix.kickoff_ts
        , fix.kickoff_time
        , case when fix.localteam_name_code = base.short_code then 'H' else 'A' end 
        , case when fix.localteam_name_code = base.short_code then fix.visitorteam_name else fix.localteam_name end 
				, case when fix.localteam_name_code = base.short_code then fix.visitorteam_name_code else fix.localteam_name_code end 
        , case when fix.localteam_name_code = base.short_code then fix.visitorteam_id else fix.localteam_id end 
        , case when fix.localteam_name_code = base.short_code then fix.localteam_score else fix.visitorteam_score end 
        , case when fix.localteam_name_code = base.short_code then fix.visitorteam_score else fix.localteam_score end 
        , `ftsy_score`
        , `appearance_ftsy`
        , `appearance_stat`
        , `captain_ftsy`
        , `captain_stats`
        , `minutes_played_ftsy`
        , `minutes_played_stat`
        , `clean_sheet_ftsy`
        , `clean_sheet_stat`
        , `goals_made_ftsy`
        , `goals_made_stat`
        , `penalties_made_ftsy`
        , `penalties_made_stat`
        , `assists_made_ftsy`
        , `assists_made_stat`
        , `owngoals_ftsy`
        , `owngoals_stat`
        , `redcards_ftsy`
        , `redcards_stat`
        , `yellowredcards_ftsy`
        , `yellowredcards_stat`
        , `dribble_attempts_ftsy`
        , `dribble_attempts_stat`
        , `dribble_success_ftsy`
        , `dribble_success_stat`
        , `dribble_fail_ftsy`
        , `dribble_fail_stat`
        , `dribbled_past_ftsy`
        , `dribbled_past_stat`
        , `duels_total_ftsy`
        , `duels_total_stat`
        , `duels_won_ftsy`
        , `duels_won_stat`
        , `duels_lost_ftsy`
        , `duels_lost_stat`
        , `fouls_drawn_ftsy`
        , `fouls_drawn_stat`
        , `fouls_committed_ftsy`
        , `fouls_committed_stat`
        , `shots_total_ftsy`
        , `shots_total_stat`
        , `shots_on_goal_ftsy`
        , `shots_on_goal_stat`
        , `shots_missed_ftsy`
        , `shots_missed_stat`
        , `shots_on_goal_saved_ftsy`
        , `shots_on_goal_saved_stat`
        , `crosses_total_ftsy`
        , `crosses_total_stat`
        , `crosses_complete_ftsy`
        , `crosses_complete_stat`
        , `crosses_incomplete_ftsy`
        , `crosses_incomplete_stat`
        , `passes_total_ftsy`
        , `passes_total_stat`
        , `passes_complete_ftsy`
        , `passes_complete_stat`
        , `passes_incomplete_ftsy`
        , `passes_incomplete_stat`
        , `passes_key_ftsy`
        , `passes_key_stat`
        , `blocks_ftsy`
        , `blocks_stat`
        , `clearances_ftsy`
        , `clearances_stat`
        , `dispossessed_ftsy`
        , `dispossessed_stat`
        , `hit_woodwork_ftsy`
        , `hit_woodwork_stat`
        , `interceptions_ftsy`
        , `interceptions_stat`
        , `offsides_ftsy`
        , `offsides_stat`
        , `tackles_ftsy`
        , `tackles_stat`
        , `inside_box_saves_ftsy`
        , `inside_box_saves_stat`
        , `outside_box_saves_ftsy`
        , `outside_box_saves_stat`
        , `saves_ftsy`
        , `saves_stat`
        , `pen_committed_ftsy`
        , `pen_committed_stat`
        , `pen_missed_ftsy`
        , `pen_missed_stat`
        , `pen_saved_ftsy`
        , `pen_saved_stat`
        , `pen_won_ftsy`
        , `pen_won_stat`

FROM `sm_playerbase_basic_v` base

INNER JOIN sm_fixtures_basic_v fix
	ON 	fix.round_name = (SELECT spieltag from parameter)
    	AND fix.season_id = (SELECT season_id from parameter)
      AND ( base.current_team_id  = fix.localteam_id or base.current_team_id = fix.visitorteam_id)
  
LEFT JOIN ftsy_scoring_akt_v scr
	ON scr.player_id = base.id

WHERE base.current_team_id IS NOT NULL
;