/* 
 * Trigger zur Materialisierung der ftsy_scoring_akt_v View
 * 
 * Erstellt eine materialisierte View (ftsy_scoring_akt_mv) die automatisch 
 * aktualisiert wird, wenn sm_player_stats für den aktuellen Spieltag geändert wird.
 * 
 * Bedingung: sm_player_stats.round_name = (SELECT round_name FROM parameter)
 * Keys: player_id, fixture_id
 */

DELIMITER $$

-- Trigger für INSERT auf sm_player_stats
CREATE TRIGGER tr_ftsy_scoring_akt_mv_insert
    AFTER INSERT ON sm_player_stats
    FOR EACH ROW
BEGIN
    DECLARE v_current_round VARCHAR(255);
    
    -- Aktuellen Spieltag aus Parameter-Tabelle holen
    SELECT spieltag INTO v_current_round 
    FROM parameter 
    LIMIT 1;
    
    -- Nur ausführen wenn der neue Datensatz dem aktuellen Spieltag entspricht
    IF NEW.round_name = v_current_round THEN
        
        -- Materialized View aktualisieren per MERGE JOIN
        INSERT INTO ftsy_scoring_akt_mv (
            fixture_id,
            player_id,
            player_name,
            position_short,
            own_team_code,
            opp_team_code,
            appearance_ftsy,
            appearance_stat,
            minutes_played_ftsy,
            minutes_played_stat,
            goals_total_ftsy,
            goals_total_stat,
            goals_minus_pen_ftsy,
            goals_minus_pen_stat,
            assists_ftsy,
            assists_stat,
            big_chances_created_ftsy,
            big_chances_created_stat,
            key_passes_ftsy,
            key_passes_stat,
            passes_total_ftsy,
            passes_total_stat,
            passes_complete_ftsy,
            passes_complete_stat,
            passes_incomplete_ftsy,
            passes_incomplete_stat,
            passes_accuracy_ftsy,
            passes_accuracy_stat,
            crosses_total_ftsy,
            crosses_total_stat,
            crosses_complete_ftsy,
            crosses_complete_stat,
            crosses_incomplete_ftsy,
            crosses_incomplete_stat,
            shots_total_ftsy,
            shots_total_stat,
            shots_on_goal_ftsy,
            shots_on_goal_stat,
            shots_missed_ftsy,
            shots_missed_stat,
            shots_blocked_ftsy,
            shots_blocked_stat,
            big_chances_missed_ftsy,
            big_chances_missed_stat,
            hit_woodwork_ftsy,
            hit_woodwork_stat,
            pen_committed_ftsy,
            pen_committed_stat,
            pen_missed_ftsy,
            pen_missed_stat,
            pen_saved_ftsy,
            pen_saved_stat,
            pen_scored_ftsy,
            pen_scored_stat,
            pen_won_ftsy,
            pen_won_stat,
            duels_total_ftsy,
            duels_total_stat,
            duels_won_ftsy,
            duels_won_stat,
            duels_lost_ftsy,
            duels_lost_stat,
            dribble_attempts_ftsy,
            dribble_attempts_stat,
            dribbles_success_ftsy,
            dribbles_success_stat,
            dribbles_failed_ftsy,
            dribbles_failed_stat,
            clean_sheet_ftsy,
            clean_sheet_stat,
            goals_conceded_ftsy,
            goals_conceded_stat,
            goalkeeper_goals_conceded_ftsy,
            goalkeeper_goals_conceded_stat,
            interceptions_ftsy,
            interceptions_stat,
            blocks_ftsy,
            blocks_stat,
            clearances_ftsy,
            clearances_stat,
            clearances_offline_ftsy,
            clearances_offline_stat,
            tackles_ftsy,
            tackles_stat,
            error_lead_to_goal_ftsy,
            error_lead_to_goal_stat,
            owngoals_ftsy,
            owngoals_stat,
            dispossessed_ftsy,
            dispossessed_stat,
            dribbled_past_ftsy,
            dribbled_past_stat,
            saves_ftsy,
            saves_stat,
            inside_box_saves_ftsy,
            inside_box_saves_stat,
            outside_box_saves_ftsy,
            outside_box_saves_stat,
            punches_ftsy,
            punches_stat,
            redcards_ftsy,
            redcards_stat,
            redyellowcards_ftsy,
            redyellowcards_stat,
            ftsy_score,
            update_ts
        )
        SELECT 
            fixture_id,
            player_id,
            player_name,
            position_short,
            own_team_code,
            opp_team_code,
            appearance_ftsy,
            appearance_stat,
            minutes_played_ftsy,
            minutes_played_stat,
            goals_total_ftsy,
            goals_total_stat,
            goals_minus_pen_ftsy,
            goals_minus_pen_stat,
            assists_ftsy,
            assists_stat,
            big_chances_created_ftsy,
            big_chances_created_stat,
            key_passes_ftsy,
            key_passes_stat,
            passes_total_ftsy,
            passes_total_stat,
            passes_complete_ftsy,
            passes_complete_stat,
            passes_incomplete_ftsy,
            passes_incomplete_stat,
            passes_accuracy_ftsy,
            passes_accuracy_stat,
            crosses_total_ftsy,
            crosses_total_stat,
            crosses_complete_ftsy,
            crosses_complete_stat,
            crosses_incomplete_ftsy,
            crosses_incomplete_stat,
            shots_total_ftsy,
            shots_total_stat,
            shots_on_goal_ftsy,
            shots_on_goal_stat,
            shots_missed_ftsy,
            shots_missed_stat,
            shots_blocked_ftsy,
            shots_blocked_stat,
            big_chances_missed_ftsy,
            big_chances_missed_stat,
            hit_woodwork_ftsy,
            hit_woodwork_stat,
            pen_committed_ftsy,
            pen_committed_stat,
            pen_missed_ftsy,
            pen_missed_stat,
            pen_saved_ftsy,
            pen_saved_stat,
            pen_scored_ftsy,
            pen_scored_stat,
            pen_won_ftsy,
            pen_won_stat,
            duels_total_ftsy,
            duels_total_stat,
            duels_won_ftsy,
            duels_won_stat,
            duels_lost_ftsy,
            duels_lost_stat,
            dribble_attempts_ftsy,
            dribble_attempts_stat,
            dribbles_success_ftsy,
            dribbles_success_stat,
            dribbles_failed_ftsy,
            dribbles_failed_stat,
            clean_sheet_ftsy,
            clean_sheet_stat,
            goals_conceded_ftsy,
            goals_conceded_stat,
            goalkeeper_goals_conceded_ftsy,
            goalkeeper_goals_conceded_stat,
            interceptions_ftsy,
            interceptions_stat,
            blocks_ftsy,
            blocks_stat,
            clearances_ftsy,
            clearances_stat,
            clearances_offline_ftsy,
            clearances_offline_stat,
            tackles_ftsy,
            tackles_stat,
            error_lead_to_goal_ftsy,
            error_lead_to_goal_stat,
            owngoals_ftsy,
            owngoals_stat,
            dispossessed_ftsy,
            dispossessed_stat,
            dribbled_past_ftsy,
            dribbled_past_stat,
            saves_ftsy,
            saves_stat,
            inside_box_saves_ftsy,
            inside_box_saves_stat,
            outside_box_saves_ftsy,
            outside_box_saves_stat,
            punches_ftsy,
            punches_stat,
            redcards_ftsy,
            redcards_stat,
            redyellowcards_ftsy,
            redyellowcards_stat,
            ftsy_score,
            NOW()
        FROM ftsy_scoring_akt_v 
        WHERE player_id = NEW.player_id 
          AND fixture_id = NEW.fixture_id
        ON DUPLICATE KEY UPDATE
            player_name = VALUES(player_name),
            position_short = VALUES(position_short),
            own_team_code = VALUES(own_team_code),
            opp_team_code = VALUES(opp_team_code),
            appearance_ftsy = VALUES(appearance_ftsy),
            appearance_stat = VALUES(appearance_stat),
            minutes_played_ftsy = VALUES(minutes_played_ftsy),
            minutes_played_stat = VALUES(minutes_played_stat),
            goals_total_ftsy = VALUES(goals_total_ftsy),
            goals_total_stat = VALUES(goals_total_stat),
            goals_minus_pen_ftsy = VALUES(goals_minus_pen_ftsy),
            goals_minus_pen_stat = VALUES(goals_minus_pen_stat),
            assists_ftsy = VALUES(assists_ftsy),
            assists_stat = VALUES(assists_stat),
            big_chances_created_ftsy = VALUES(big_chances_created_ftsy),
            big_chances_created_stat = VALUES(big_chances_created_stat),
            key_passes_ftsy = VALUES(key_passes_ftsy),
            key_passes_stat = VALUES(key_passes_stat),
            passes_total_ftsy = VALUES(passes_total_ftsy),
            passes_total_stat = VALUES(passes_total_stat),
            passes_complete_ftsy = VALUES(passes_complete_ftsy),
            passes_complete_stat = VALUES(passes_complete_stat),
            passes_incomplete_ftsy = VALUES(passes_incomplete_ftsy),
            passes_incomplete_stat = VALUES(passes_incomplete_stat),
            passes_accuracy_ftsy = VALUES(passes_accuracy_ftsy),
            passes_accuracy_stat = VALUES(passes_accuracy_stat),
            crosses_total_ftsy = VALUES(crosses_total_ftsy),
            crosses_total_stat = VALUES(crosses_total_stat),
            crosses_complete_ftsy = VALUES(crosses_complete_ftsy),
            crosses_complete_stat = VALUES(crosses_complete_stat),
            crosses_incomplete_ftsy = VALUES(crosses_incomplete_ftsy),
            crosses_incomplete_stat = VALUES(crosses_incomplete_stat),
            shots_total_ftsy = VALUES(shots_total_ftsy),
            shots_total_stat = VALUES(shots_total_stat),
            shots_on_goal_ftsy = VALUES(shots_on_goal_ftsy),
            shots_on_goal_stat = VALUES(shots_on_goal_stat),
            shots_missed_ftsy = VALUES(shots_missed_ftsy),
            shots_missed_stat = VALUES(shots_missed_stat),
            shots_blocked_ftsy = VALUES(shots_blocked_ftsy),
            shots_blocked_stat = VALUES(shots_blocked_stat),
            big_chances_missed_ftsy = VALUES(big_chances_missed_ftsy),
            big_chances_missed_stat = VALUES(big_chances_missed_stat),
            hit_woodwork_ftsy = VALUES(hit_woodwork_ftsy),
            hit_woodwork_stat = VALUES(hit_woodwork_stat),
            pen_committed_ftsy = VALUES(pen_committed_ftsy),
            pen_committed_stat = VALUES(pen_committed_stat),
            pen_missed_ftsy = VALUES(pen_missed_ftsy),
            pen_missed_stat = VALUES(pen_missed_stat),
            pen_saved_ftsy = VALUES(pen_saved_ftsy),
            pen_saved_stat = VALUES(pen_saved_stat),
            pen_scored_ftsy = VALUES(pen_scored_ftsy),
            pen_scored_stat = VALUES(pen_scored_stat),
            pen_won_ftsy = VALUES(pen_won_ftsy),
            pen_won_stat = VALUES(pen_won_stat),
            duels_total_ftsy = VALUES(duels_total_ftsy),
            duels_total_stat = VALUES(duels_total_stat),
            duels_won_ftsy = VALUES(duels_won_ftsy),
            duels_won_stat = VALUES(duels_won_stat),
            duels_lost_ftsy = VALUES(duels_lost_ftsy),
            duels_lost_stat = VALUES(duels_lost_stat),
            dribble_attempts_ftsy = VALUES(dribble_attempts_ftsy),
            dribble_attempts_stat = VALUES(dribble_attempts_stat),
            dribbles_success_ftsy = VALUES(dribbles_success_ftsy),
            dribbles_success_stat = VALUES(dribbles_success_stat),
            dribbles_failed_ftsy = VALUES(dribbles_failed_ftsy),
            dribbles_failed_stat = VALUES(dribbles_failed_stat),
            clean_sheet_ftsy = VALUES(clean_sheet_ftsy),
            clean_sheet_stat = VALUES(clean_sheet_stat),
            goals_conceded_ftsy = VALUES(goals_conceded_ftsy),
            goals_conceded_stat = VALUES(goals_conceded_stat),
            goalkeeper_goals_conceded_ftsy = VALUES(goalkeeper_goals_conceded_ftsy),
            goalkeeper_goals_conceded_stat = VALUES(goalkeeper_goals_conceded_stat),
            interceptions_ftsy = VALUES(interceptions_ftsy),
            interceptions_stat = VALUES(interceptions_stat),
            blocks_ftsy = VALUES(blocks_ftsy),
            blocks_stat = VALUES(blocks_stat),
            clearances_ftsy = VALUES(clearances_ftsy),
            clearances_stat = VALUES(clearances_stat),
            clearances_offline_ftsy = VALUES(clearances_offline_ftsy),
            clearances_offline_stat = VALUES(clearances_offline_stat),
            tackles_ftsy = VALUES(tackles_ftsy),
            tackles_stat = VALUES(tackles_stat),
            error_lead_to_goal_ftsy = VALUES(error_lead_to_goal_ftsy),
            error_lead_to_goal_stat = VALUES(error_lead_to_goal_stat),
            owngoals_ftsy = VALUES(owngoals_ftsy),
            owngoals_stat = VALUES(owngoals_stat),
            dispossessed_ftsy = VALUES(dispossessed_ftsy),
            dispossessed_stat = VALUES(dispossessed_stat),
            dribbled_past_ftsy = VALUES(dribbled_past_ftsy),
            dribbled_past_stat = VALUES(dribbled_past_stat),
            saves_ftsy = VALUES(saves_ftsy),
            saves_stat = VALUES(saves_stat),
            inside_box_saves_ftsy = VALUES(inside_box_saves_ftsy),
            inside_box_saves_stat = VALUES(inside_box_saves_stat),
            outside_box_saves_ftsy = VALUES(outside_box_saves_ftsy),
            outside_box_saves_stat = VALUES(outside_box_saves_stat),
            punches_ftsy = VALUES(punches_ftsy),
            punches_stat = VALUES(punches_stat),
            redcards_ftsy = VALUES(redcards_ftsy),
            redcards_stat = VALUES(redcards_stat),
            redyellowcards_ftsy = VALUES(redyellowcards_ftsy),
            redyellowcards_stat = VALUES(redyellowcards_stat),
            ftsy_score = VALUES(ftsy_score),
            update_ts = VALUES(update_ts);
            
    END IF;
END$$

-- Trigger für UPDATE auf sm_player_stats
CREATE TRIGGER tr_ftsy_scoring_akt_mv_update
    AFTER UPDATE ON sm_player_stats
    FOR EACH ROW
BEGIN
    DECLARE v_current_round VARCHAR(255);
    
    -- Aktuellen Spieltag aus Parameter-Tabelle holen
    SELECT spieltag INTO v_current_round 
    FROM parameter 
    LIMIT 1;
    
    -- Nur ausführen wenn der geänderte Datensatz dem aktuellen Spieltag entspricht
    IF NEW.round_name = v_current_round THEN
        
        -- Materialized View aktualisieren per MERGE JOIN
        INSERT INTO ftsy_scoring_akt_mv (
            fixture_id,
            player_id,
            player_name,
            position_short,
            own_team_code,
            opp_team_code,
            appearance_ftsy,
            appearance_stat,
            minutes_played_ftsy,
            minutes_played_stat,
            goals_total_ftsy,
            goals_total_stat,
            goals_minus_pen_ftsy,
            goals_minus_pen_stat,
            assists_ftsy,
            assists_stat,
            big_chances_created_ftsy,
            big_chances_created_stat,
            key_passes_ftsy,
            key_passes_stat,
            passes_total_ftsy,
            passes_total_stat,
            passes_complete_ftsy,
            passes_complete_stat,
            passes_incomplete_ftsy,
            passes_incomplete_stat,
            passes_accuracy_ftsy,
            passes_accuracy_stat,
            crosses_total_ftsy,
            crosses_total_stat,
            crosses_complete_ftsy,
            crosses_complete_stat,
            crosses_incomplete_ftsy,
            crosses_incomplete_stat,
            shots_total_ftsy,
            shots_total_stat,
            shots_on_goal_ftsy,
            shots_on_goal_stat,
            shots_missed_ftsy,
            shots_missed_stat,
            shots_blocked_ftsy,
            shots_blocked_stat,
            big_chances_missed_ftsy,
            big_chances_missed_stat,
            hit_woodwork_ftsy,
            hit_woodwork_stat,
            pen_committed_ftsy,
            pen_committed_stat,
            pen_missed_ftsy,
            pen_missed_stat,
            pen_saved_ftsy,
            pen_saved_stat,
            pen_scored_ftsy,
            pen_scored_stat,
            pen_won_ftsy,
            pen_won_stat,
            duels_total_ftsy,
            duels_total_stat,
            duels_won_ftsy,
            duels_won_stat,
            duels_lost_ftsy,
            duels_lost_stat,
            dribble_attempts_ftsy,
            dribble_attempts_stat,
            dribbles_success_ftsy,
            dribbles_success_stat,
            dribbles_failed_ftsy,
            dribbles_failed_stat,
            clean_sheet_ftsy,
            clean_sheet_stat,
            goals_conceded_ftsy,
            goals_conceded_stat,
            goalkeeper_goals_conceded_ftsy,
            goalkeeper_goals_conceded_stat,
            interceptions_ftsy,
            interceptions_stat,
            blocks_ftsy,
            blocks_stat,
            clearances_ftsy,
            clearances_stat,
            clearances_offline_ftsy,
            clearances_offline_stat,
            tackles_ftsy,
            tackles_stat,
            error_lead_to_goal_ftsy,
            error_lead_to_goal_stat,
            owngoals_ftsy,
            owngoals_stat,
            dispossessed_ftsy,
            dispossessed_stat,
            dribbled_past_ftsy,
            dribbled_past_stat,
            saves_ftsy,
            saves_stat,
            inside_box_saves_ftsy,
            inside_box_saves_stat,
            outside_box_saves_ftsy,
            outside_box_saves_stat,
            punches_ftsy,
            punches_stat,
            redcards_ftsy,
            redcards_stat,
            redyellowcards_ftsy,
            redyellowcards_stat,
            ftsy_score,
            update_ts
        )
        SELECT 
            fixture_id,
            player_id,
            player_name,
            position_short,
            own_team_code,
            opp_team_code,
            appearance_ftsy,
            appearance_stat,
            minutes_played_ftsy,
            minutes_played_stat,
            goals_total_ftsy,
            goals_total_stat,
            goals_minus_pen_ftsy,
            goals_minus_pen_stat,
            assists_ftsy,
            assists_stat,
            big_chances_created_ftsy,
            big_chances_created_stat,
            key_passes_ftsy,
            key_passes_stat,
            passes_total_ftsy,
            passes_total_stat,
            passes_complete_ftsy,
            passes_complete_stat,
            passes_incomplete_ftsy,
            passes_incomplete_stat,
            passes_accuracy_ftsy,
            passes_accuracy_stat,
            crosses_total_ftsy,
            crosses_total_stat,
            crosses_complete_ftsy,
            crosses_complete_stat,
            crosses_incomplete_ftsy,
            crosses_incomplete_stat,
            shots_total_ftsy,
            shots_total_stat,
            shots_on_goal_ftsy,
            shots_on_goal_stat,
            shots_missed_ftsy,
            shots_missed_stat,
            shots_blocked_ftsy,
            shots_blocked_stat,
            big_chances_missed_ftsy,
            big_chances_missed_stat,
            hit_woodwork_ftsy,
            hit_woodwork_stat,
            pen_committed_ftsy,
            pen_committed_stat,
            pen_missed_ftsy,
            pen_missed_stat,
            pen_saved_ftsy,
            pen_saved_stat,
            pen_scored_ftsy,
            pen_scored_stat,
            pen_won_ftsy,
            pen_won_stat,
            duels_total_ftsy,
            duels_total_stat,
            duels_won_ftsy,
            duels_won_stat,
            duels_lost_ftsy,
            duels_lost_stat,
            dribble_attempts_ftsy,
            dribble_attempts_stat,
            dribbles_success_ftsy,
            dribbles_success_stat,
            dribbles_failed_ftsy,
            dribbles_failed_stat,
            clean_sheet_ftsy,
            clean_sheet_stat,
            goals_conceded_ftsy,
            goals_conceded_stat,
            goalkeeper_goals_conceded_ftsy,
            goalkeeper_goals_conceded_stat,
            interceptions_ftsy,
            interceptions_stat,
            blocks_ftsy,
            blocks_stat,
            clearances_ftsy,
            clearances_stat,
            clearances_offline_ftsy,
            clearances_offline_stat,
            tackles_ftsy,
            tackles_stat,
            error_lead_to_goal_ftsy,
            error_lead_to_goal_stat,
            owngoals_ftsy,
            owngoals_stat,
            dispossessed_ftsy,
            dispossessed_stat,
            dribbled_past_ftsy,
            dribbled_past_stat,
            saves_ftsy,
            saves_stat,
            inside_box_saves_ftsy,
            inside_box_saves_stat,
            outside_box_saves_ftsy,
            outside_box_saves_stat,
            punches_ftsy,
            punches_stat,
            redcards_ftsy,
            redcards_stat,
            redyellowcards_ftsy,
            redyellowcards_stat,
            ftsy_score,
            NOW()
        FROM ftsy_scoring_akt_v 
        WHERE player_id = NEW.player_id 
          AND fixture_id = NEW.fixture_id
        ON DUPLICATE KEY UPDATE
            player_name = VALUES(player_name),
            position_short = VALUES(position_short),
            own_team_code = VALUES(own_team_code),
            opp_team_code = VALUES(opp_team_code),
            appearance_ftsy = VALUES(appearance_ftsy),
            appearance_stat = VALUES(appearance_stat),
            minutes_played_ftsy = VALUES(minutes_played_ftsy),
            minutes_played_stat = VALUES(minutes_played_stat),
            goals_total_ftsy = VALUES(goals_total_ftsy),
            goals_total_stat = VALUES(goals_total_stat),
            goals_minus_pen_ftsy = VALUES(goals_minus_pen_ftsy),
            goals_minus_pen_stat = VALUES(goals_minus_pen_stat),
            assists_ftsy = VALUES(assists_ftsy),
            assists_stat = VALUES(assists_stat),
            big_chances_created_ftsy = VALUES(big_chances_created_ftsy),
            big_chances_created_stat = VALUES(big_chances_created_stat),
            key_passes_ftsy = VALUES(key_passes_ftsy),
            key_passes_stat = VALUES(key_passes_stat),
            passes_total_ftsy = VALUES(passes_total_ftsy),
            passes_total_stat = VALUES(passes_total_stat),
            passes_complete_ftsy = VALUES(passes_complete_ftsy),
            passes_complete_stat = VALUES(passes_complete_stat),
            passes_incomplete_ftsy = VALUES(passes_incomplete_ftsy),
            passes_incomplete_stat = VALUES(passes_incomplete_stat),
            passes_accuracy_ftsy = VALUES(passes_accuracy_ftsy),
            passes_accuracy_stat = VALUES(passes_accuracy_stat),
            crosses_total_ftsy = VALUES(crosses_total_ftsy),
            crosses_total_stat = VALUES(crosses_total_stat),
            crosses_complete_ftsy = VALUES(crosses_complete_ftsy),
            crosses_complete_stat = VALUES(crosses_complete_stat),
            crosses_incomplete_ftsy = VALUES(crosses_incomplete_ftsy),
            crosses_incomplete_stat = VALUES(crosses_incomplete_stat),
            shots_total_ftsy = VALUES(shots_total_ftsy),
            shots_total_stat = VALUES(shots_total_stat),
            shots_on_goal_ftsy = VALUES(shots_on_goal_ftsy),
            shots_on_goal_stat = VALUES(shots_on_goal_stat),
            shots_missed_ftsy = VALUES(shots_missed_ftsy),
            shots_missed_stat = VALUES(shots_missed_stat),
            shots_blocked_ftsy = VALUES(shots_blocked_ftsy),
            shots_blocked_stat = VALUES(shots_blocked_stat),
            big_chances_missed_ftsy = VALUES(big_chances_missed_ftsy),
            big_chances_missed_stat = VALUES(big_chances_missed_stat),
            hit_woodwork_ftsy = VALUES(hit_woodwork_ftsy),
            hit_woodwork_stat = VALUES(hit_woodwork_stat),
            pen_committed_ftsy = VALUES(pen_committed_ftsy),
            pen_committed_stat = VALUES(pen_committed_stat),
            pen_missed_ftsy = VALUES(pen_missed_ftsy),
            pen_missed_stat = VALUES(pen_missed_stat),
            pen_saved_ftsy = VALUES(pen_saved_ftsy),
            pen_saved_stat = VALUES(pen_saved_stat),
            pen_scored_ftsy = VALUES(pen_scored_ftsy),
            pen_scored_stat = VALUES(pen_scored_stat),
            pen_won_ftsy = VALUES(pen_won_ftsy),
            pen_won_stat = VALUES(pen_won_stat),
            duels_total_ftsy = VALUES(duels_total_ftsy),
            duels_total_stat = VALUES(duels_total_stat),
            duels_won_ftsy = VALUES(duels_won_ftsy),
            duels_won_stat = VALUES(duels_won_stat),
            duels_lost_ftsy = VALUES(duels_lost_ftsy),
            duels_lost_stat = VALUES(duels_lost_stat),
            dribble_attempts_ftsy = VALUES(dribble_attempts_ftsy),
            dribble_attempts_stat = VALUES(dribble_attempts_stat),
            dribbles_success_ftsy = VALUES(dribbles_success_ftsy),
            dribbles_success_stat = VALUES(dribbles_success_stat),
            dribbles_failed_ftsy = VALUES(dribbles_failed_ftsy),
            dribbles_failed_stat = VALUES(dribbles_failed_stat),
            clean_sheet_ftsy = VALUES(clean_sheet_ftsy),
            clean_sheet_stat = VALUES(clean_sheet_stat),
            goals_conceded_ftsy = VALUES(goals_conceded_ftsy),
            goals_conceded_stat = VALUES(goals_conceded_stat),
            goalkeeper_goals_conceded_ftsy = VALUES(goalkeeper_goals_conceded_ftsy),
            goalkeeper_goals_conceded_stat = VALUES(goalkeeper_goals_conceded_stat),
            interceptions_ftsy = VALUES(interceptions_ftsy),
            interceptions_stat = VALUES(interceptions_stat),
            blocks_ftsy = VALUES(blocks_ftsy),
            blocks_stat = VALUES(blocks_stat),
            clearances_ftsy = VALUES(clearances_ftsy),
            clearances_stat = VALUES(clearances_stat),
            clearances_offline_ftsy = VALUES(clearances_offline_ftsy),
            clearances_offline_stat = VALUES(clearances_offline_stat),
            tackles_ftsy = VALUES(tackles_ftsy),
            tackles_stat = VALUES(tackles_stat),
            error_lead_to_goal_ftsy = VALUES(error_lead_to_goal_ftsy),
            error_lead_to_goal_stat = VALUES(error_lead_to_goal_stat),
            owngoals_ftsy = VALUES(owngoals_ftsy),
            owngoals_stat = VALUES(owngoals_stat),
            dispossessed_ftsy = VALUES(dispossessed_ftsy),
            dispossessed_stat = VALUES(dispossessed_stat),
            dribbled_past_ftsy = VALUES(dribbled_past_ftsy),
            dribbled_past_stat = VALUES(dribbled_past_stat),
            saves_ftsy = VALUES(saves_ftsy),
            saves_stat = VALUES(saves_stat),
            inside_box_saves_ftsy = VALUES(inside_box_saves_ftsy),
            inside_box_saves_stat = VALUES(inside_box_saves_stat),
            outside_box_saves_ftsy = VALUES(outside_box_saves_ftsy),
            outside_box_saves_stat = VALUES(outside_box_saves_stat),
            punches_ftsy = VALUES(punches_ftsy),
            punches_stat = VALUES(punches_stat),
            redcards_ftsy = VALUES(redcards_ftsy),
            redcards_stat = VALUES(redcards_stat),
            redyellowcards_ftsy = VALUES(redyellowcards_ftsy),
            redyellowcards_stat = VALUES(redyellowcards_stat),
            ftsy_score = VALUES(ftsy_score),
            update_ts = VALUES(update_ts);
            
    END IF;
END$$

DELIMITER ;