UPDATE ftsy_scoring_hist hst

INNER JOIN sm_player_stats st
	ON 	hst.fixture_id= st.fixture_id
    	AND hst.player_id= st.player_id
        
SET   hst.round_name = st.round_name
      , hst.appearance_stat = st.appearance
      , hst.minutes_played_stat = st.minutes_played
      , hst.goals_total_stat = st.goals_total
      , hst.goals_minus_pen_stat = st.goals_minus_pen
      , hst.assists_stat = st.assists
      , hst.big_chances_created_stat = st.big_chances_created
      , hst.key_passes_stat = st.key_passes
      , hst.passes_total_stat = st.passes_total
      , hst.passes_complete_stat = st.passes_complete
      , hst.passes_incomplete_stat = st.passes_incomplete
      , hst.passes_accuracy_stat = st.passes_accuracy
      , hst.crosses_total_stat = st.crosses_total
      , hst.crosses_complete_stat = st.crosses_complete
      , hst.crosses_incomplete_stat = st.crosses_incomplete
      , hst.shots_total_stat = st.shots_total
      , hst.shots_on_goal_stat = st.shots_on_goal
      , hst.shots_missed_stat = st.shots_missed
      , hst.shots_blocked_stat = st.shots_blocked
      , hst.big_chances_missed_stat = st.big_chances_missed
      , hst.hit_woodwork_stat = st.hit_woodwork
      , hst.pen_committed_stat = st.pen_committed
      , hst.pen_missed_stat = st.pen_missed
      , hst.pen_saved_stat = st.pen_saved
      , hst.pen_scored_stat = st.pen_scored
      , hst.pen_won_stat = st.pen_won
      , hst.duels_total_stat = st.duels_total
      , hst.duels_won_stat = st.duels_won
      , hst.duels_lost_stat = st.duels_lost 
      , hst.dribble_attempts_stat = st.dribble_attempts
      , hst.dribbles_success_stat = st.dribbles_success
      , hst.dribbles_failed_stat = st.dribbles_failed
      , hst.clean_sheet_stat = st.clean_sheet
      , hst.goals_conceded_stat = st.goals_conceded
      , hst.goalkeeper_goals_conceded_stat = st.goalkeeper_goals_conceded
      , hst.interceptions_stat = st.interceptions
      , hst.blocks_stat = st.blocks
      , hst.clearances_stat = st.clearances
      , hst.clearances_offline_stat = st.clearance_offline
      , hst.tackles_stat = st.tackles
      , hst.error_lead_to_goal_stat = st.error_lead_to_goal
      , hst.owngoals_stat = st.owngoals
      , hst.dispossessed_stat = st.dispossessed
      , hst.dribbled_past_stat = st.dribbled_past
      , hst.saves_stat = st.saves
      , hst.inside_box_saves_stat = st.inside_box_saves
      , hst.outside_box_saves_stat = st.outside_box_saves
      , hst.punches_stat = st.punches
      , hst.redcards_stat = st.redcards
      , hst.redyellowcards_stat = st.redyellowcards
      , hst.update_ts = sysdate();